services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    command: /bin/bash
    tty: true
    volumes:
      - .:/workspace
    working_dir: /workspace
